trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '02-Terraform-Basics/02-02-Terraform-Command-Basics/terraform-manifests/'
    backendServiceAWS: 'aws-terraform-us-east-2'
    backendAWSBucketName: 'infra-state-frcm'
    backendAWSKey: 'ec2-state/ec2-state'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: '02-Terraform-Basics/02-02-Terraform-Command-Basics/terraform-manifests'
    commandOptions: '-no-color'
    environmentServiceNameAWS: 'Terraform-us-east-2'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '02-Terraform-Basics/02-02-Terraform-Command-Basics/terraform-manifests'
    commandOptions: '-auto-approve'
    environmentServiceNameAWS: 'Terraform-us-east-2'
